cache: pip

matrix:
  include:
    - os: linux
      dist: precise
      python: 3.6
      language: python
    - os: linux
      dist: trusty
      python: 3.6
      language: python
    - os: linux
      dist: trusty
      python: 3.5
      sudo: required
      language: python
      compiler: clang
      env: COMPILER='clang-3.9'
      addons:
        apt:
          sources:
            - ['llvm-toolchain-trusty-3.9', 'ubuntu-toolchain-r-test']
          packages:
            - 'clang-3.9'
    - os: linux
      dist: trusty
      python: 3.6
      sudo: required
      language: python
      compiler: gcc
      env: COMPILER='gcc-6'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
    - os: osx
      osx_image: xcode7.3
      language: generic
    - os: osx
      osx_image: xcode8.2
      language: generic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then if [[ "$COMPILER" == g* ]]; then sudo update-alternatives --install /usr/bin/gcc gcc "/usr/bin/${COMPILER}" 1; export CC="${COMPILER}"; fi; fi

install:
  - pip3 install -U setuptools wheel
  - python3 setup.py install

script: python3 test.py
