sudo: required
dist: trusty
language: python
matrix:
  include:
  - services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32
install:
- docker pull $DOCKER_IMAGE
script:
- docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
- ls wheelhouse/
after_success:
- openssl aes-256-cbc -K $encrypted_0a601b1cd6e7_key -iv $encrypted_0a601b1cd6e7_iv
  -in travis/.pypirc.enc -out .pypirc -d
- travis/upload-wheels.sh
